# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myplaylist.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPlaylist(object):
    def setupUi(self, MainPlaylist):
        MainPlaylist.setObjectName("MainPlaylist")
        MainPlaylist.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainPlaylist)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 510, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(6, 0, 791, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.listWidget_2 = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.listWidget_2.setObjectName("listWidget_2")
        self.horizontalLayout.addWidget(self.listWidget_2)
        MainPlaylist.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainPlaylist)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainPlaylist.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainPlaylist)
        self.statusbar.setObjectName("statusbar")
        MainPlaylist.setStatusBar(self.statusbar)

        self.retranslateUi(MainPlaylist)
        QtCore.QMetaObject.connectSlotsByName(MainPlaylist)

    def retranslateUi(self, MainPlaylist):
        _translate = QtCore.QCoreApplication.translate
        MainPlaylist.setWindowTitle(_translate("MainPlaylist", "MainWindow"))
        self.pushButton.setText(_translate("MainPlaylist", "Add music"))
